const base = "d15zfgfl7yuxem.cloudfront.net"
import functions from "../structures/Functions"

const getCover = (title) => {
    if (functions.isLocalHost()) return getLocalCover(title)
    return functions.encodeS3URI(`https://${base}/nsfw/covers/${title}.jpg`)
}

const getVolumes = (title) => {
    if (functions.isLocalHost()) return getLocalVolumes(title)
    let volumes = []
    volumes.push({
        volumeNumber: 1,
        cover: functions.encodeS3URI(`https://${base}/nsfw/covers/${title}.jpg`),
        japaneseSource: functions.encodeS3URI(`https://${base}/nsfw/japanese/${title}.pdf`),
        englishSource: functions.encodeS3URI(`https://${base}/nsfw/english/${title}.pdf`)
    })
    return volumes
}

const getLocalCover = (title) => {
    return `/Manga/NSFW/Covers/${title}.jpg`
}

const getLocalVolumes = (title) => {
    let volumes = []
    volumes.push({
        volumeNumber: 1,
        cover: `/Manga/NSFW/Covers/${title}.jpg`,
        japaneseSource: `/Manga/NSFW/Japanese/${title}.pdf`,
        englishSource: `/Manga/NSFW/English/${title}.pdf`
    })
    return volumes
}

export default [
    {
        title: "Karen Complex",
        id: "karen-complex",
        hidden: true,
        japaneseTitle: "カレンコンプレックス",
        artists: ["Kujou Danbo"],
        published: "May 2016",
        added: "2023-02-01T01:22:41.656Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "https://www.melonbooks.co.jp/detail/detail.php?product_id=161845",
        cover: getCover("Karen Complex"),
        volumeCount: 1,
        volumes: getVolumes("Karen Complex")
    },
    {
        title: "Iroiro Ikuiku",
        id: "iroiro-ikuiku",
        hidden: true,
        japaneseTitle: "いろいろイクイク",
        artists: ["Kannazuki Motofumi"],
        published: "July 2015",
        added: "2023-02-01T01:47:20.388Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "https://www.pixiv.net/en/artworks/51533148",
        cover: getCover("Iroiro Ikuiku"),
        volumeCount: 1,
        volumes: getVolumes("Iroiro Ikuiku")
    },
    {
        title: "Moro Iku",
        id: "moro-iku",
        hidden: true,
        japaneseTitle: "モろイク。",
        artists: ["Kannazuki Motofumi"],
        published: "August 2013",
        added: "2023-02-01T01:47:24.989Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "https://www.melonbooks.co.jp/detail/detail.php?product_id=244712",
        cover: getCover("Moro Iku"),
        volumeCount: 1,
        volumes: getVolumes("Moro Iku")
    },
    {
        title: "Albino Sakura-chan to Ama Ecchi",
        id: "albino-sakura-chan-to-ama-ecchi",
        hidden: true,
        japaneseTitle: "アルビノ桜ちゃんとあまえっち",
        artists: ["Usashiro Mani"],
        published: "April 2019",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "https://www.melonbooks.co.jp/detail/detail.php?product_id=499675",
        cover: getCover("Albino Sakura-chan to Ama Ecchi"),
        volumeCount: 1,
        volumes: getVolumes("Albino Sakura-chan to Ama Ecchi")
    },
    {
        title: "Alma ga Arekore Sareru no o Nagameru Hon 4",
        id: "alma-ga-arekore-sareru-no-o-nagameru-hon-4",
        hidden: true,
        japaneseTitle: "アルマがアレコレされるのを眺める本。4",
        artists: ["Maya Gorou"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Alma ga Arekore Sareru no o Nagameru Hon 4"),
        volumeCount: 1,
        volumes: getVolumes("Alma ga Arekore Sareru no o Nagameru Hon 4")
    },
    {
        title: "Alma ga Arekore Sareru no o Nagameru Hon 6",
        id: "alma-ga-arekore-sareru-no-o-nagameru-hon-6",
        hidden: true,
        japaneseTitle: "アルマがアレコレされるのを眺める本。6",
        artists: ["Maya Gorou"],
        published: "August 2019",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "https://www.melonbooks.co.jp/detail/detail.php?product_id=552212",
        cover: getCover("Alma ga Arekore Sareru no o Nagameru Hon 6"),
        volumeCount: 1,
        volumes: getVolumes("Alma ga Arekore Sareru no o Nagameru Hon 6")
    },
    {
        title: "Alma ga Arekore Sareru no o Nagameru Hon 7",
        id: "alma-ga-arekore-sareru-no-o-nagameru-hon-7",
        hidden: true,
        japaneseTitle: "アルマがアレコレされるのを眺める本。7",
        artists: ["Maya Gorou"],
        published: "December 2019",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "https://www.melonbooks.co.jp/detail/detail.php?product_id=616764",
        cover: getCover("Alma ga Arekore Sareru no o Nagameru Hon 7"),
        volumeCount: 1,
        volumes: getVolumes("Alma ga Arekore Sareru no o Nagameru Hon 7")
    },
    {
        title: "Chimahame",
        id: "chimahame",
        hidden: true,
        japaneseTitle: "チマハメ",
        artists: ["Kannazuki Motofumi"],
        published: "January 2016",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "https://www.melonbooks.co.jp/detail/detail.php?product_id=242272",
        cover: getCover("Chimahame"),
        volumeCount: 1,
        volumes: getVolumes("Chimahame")
    },
    {
        title: "Chimame Seifuku Ikaga desu ka",
        id: "chimame-seifuku-ikaga-desu-ka",
        hidden: true,
        japaneseTitle: "チマメ制服いかがですか?",
        artists: ["Komone Ushio"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Chimame Seifuku Ikaga desu ka"),
        volumeCount: 1,
        volumes: getVolumes("Chimame Seifuku Ikaga desu ka")
    },
    {
        title: "Cocoa Holic #20 Chino Holic",
        id: "cocoa-holic-#20-chino-holic",
        hidden: true,
        japaneseTitle: "Cocoa Holic #20 チノホリック",
        artists: ["Yuizaki Kazuya"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Cocoa Holic %2320 Chino Holic"),
        volumeCount: 1,
        volumes: getVolumes("Cocoa Holic %2320 Chino Holic")
    },
    {
        title: "Cocoa Holic #22 Chino Holic 2",
        id: "cocoa-holic-#22-chino-holic-2",
        hidden: true,
        japaneseTitle: "Cocoa Holic #22 チノホリック 2",
        artists: ["Yuizaki Kazuya"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Cocoa Holic %2322 Chino Holic 2"),
        volumeCount: 1,
        volumes: getVolumes("Cocoa Holic %2322 Chino Holic 2")
    },
    {
        title: "Control Dropout",
        id: "control-dropout",
        hidden: true,
        japaneseTitle: "コントロールドロップアウト",
        artists: ["Mizushina Minato"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Control Dropout"),
        volumeCount: 1,
        volumes: getVolumes("Control Dropout")
    },
    {
        title: "DATSUSHIN",
        id: "datsushin",
        hidden: true,
        japaneseTitle: "脱神",
        artists: ["Fujima Takuya", "Yan-Yam"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("DATSUSHIN"),
        volumeCount: 1,
        volumes: getVolumes("DATSUSHIN")
    },
    {
        title: "Dreamy Desserts Kai Ni",
        id: "dreamy-desserts-kai-ni",
        hidden: true,
        japaneseTitle: "Dreamy Desserts改二",
        artists: ["Imachi"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Dreamy Desserts Kai Ni"),
        volumeCount: 1,
        volumes: getVolumes("Dreamy Desserts Kai Ni")
    },
    {
        title: "Ero☆Pa! - Eromanga☆Party!",
        id: "ero☆pa!---eromanga☆party!",
        hidden: true,
        japaneseTitle: "エロ☆パ!",
        artists: ["Fujima Takuya"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Ero☆Pa! - Eromanga☆Party!"),
        volumeCount: 1,
        volumes: getVolumes("Ero☆Pa! - Eromanga☆Party!")
    },
    {
        title: "Fuwafuwa no Koi dakara",
        id: "fuwafuwa-no-koi-dakara",
        hidden: true,
        japaneseTitle: "ふわふわの恋だから。",
        artists: ["Usashiro Mani"],
        published: "August 2018",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Fuwafuwa no Koi dakara"),
        volumeCount: 1,
        volumes: getVolumes("Fuwafuwa no Koi dakara")
    },
    {
        title: "GaCen Hime to DT Otoko no Ichaicha Kozukuri Love Sex",
        id: "gacen-hime-to-dt-otoko-no-ichaicha-kozukuri-love-sex",
        hidden: true,
        japaneseTitle: "ゲーセン姫とDT男のイチャイチャ子作りラブセックス",
        artists: ["Usashiro Mani"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("GaCen Hime to DT Otoko no Ichaicha Kozukuri Love Sex"),
        volumeCount: 1,
        volumes: getVolumes("GaCen Hime to DT Otoko no Ichaicha Kozukuri Love Sex")
    },
    {
        title: "Gomen ne Ikazuchi-chan",
        id: "gomen-ne-ikazuchi-chan",
        hidden: true,
        japaneseTitle: "ごめんね雷ちゃん",
        artists: ["Marugoshi"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Gomen ne Ikazuchi-chan"),
        volumeCount: 1,
        volumes: getVolumes("Gomen ne Ikazuchi-chan")
    },
    {
        title: "Hibiki-chan Himitsu no Hatsu Sounyuu",
        id: "hibiki-chan-himitsu-no-hatsu-sounyuu",
        hidden: true,
        japaneseTitle: "響ちゃんヒミツの初挿入",
        artists: ["Watanon"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Hibiki-chan Himitsu no Hatsu Sounyuu"),
        volumeCount: 1,
        volumes: getVolumes("Hibiki-chan Himitsu no Hatsu Sounyuu")
    },
    {
        title: "Kitsune no Ekichou-san",
        id: "kitsune-no-ekichou-san",
        hidden: true,
        japaneseTitle: "キツネの駅長さん",
        artists: ["Ameto Yuki"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Kitsune no Ekichou-san"),
        volumeCount: 1,
        volumes: getVolumes("Kitsune no Ekichou-san")
    },
    {
        title: "KokoSharo de Yuri ni Mezameru Hon",
        id: "kokosharo-de-yuri-ni-mezameru-hon",
        hidden: true,
        japaneseTitle: "ココシャロで百合に目覚める本",
        artists: ["Nanakusa Amane"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("KokoSharo de Yuri ni Mezameru Hon"),
        volumeCount: 1,
        volumes: getVolumes("KokoSharo de Yuri ni Mezameru Hon")
    },
    {
        title: "Nemurenu Laffey no Shitsukekata",
        id: "nemurenu-laffey-no-shitsukekata",
        hidden: true,
        japaneseTitle: "眠れぬ兎のしつけかた",
        artists: ["Rokusyou Kokuu"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Nemurenu Laffey no Shitsukekata"),
        volumeCount: 1,
        volumes: getVolumes("Nemurenu Laffey no Shitsukekata")
    },
    {
        title: "Nenecchi Abunai yo!",
        id: "nenecchi-abunai-yo!",
        hidden: true,
        japaneseTitle: "ねねっちあぶないよ!",
        artists: ["Kokekokko Coma"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Nenecchi Abunai yo!"),
        volumeCount: 1,
        volumes: getVolumes("Nenecchi Abunai yo!")
    },
    {
        title: "Ookami Tetsudou e Youkoso!",
        id: "ookami-tetsudou-e-youkoso!",
        hidden: true,
        japaneseTitle: "おおかみ鉄道へようこそ!",
        artists: ["Ameto Yuki"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Ookami Tetsudou e Youkoso!"),
        volumeCount: 1,
        volumes: getVolumes("Ookami Tetsudou e Youkoso!")
    },
    {
        title: "Saimin nante Kakaru Wake Naijanaidesuka",
        id: "saimin-nante-kakaru-wake-naijanaidesuka",
        hidden: true,
        japaneseTitle: "催眠なんてかかるわけないじゃないですか",
        artists: ["typehatena"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Saimin nante Kakaru Wake Naijanaidesuka"),
        volumeCount: 1,
        volumes: getVolumes("Saimin nante Kakaru Wake Naijanaidesuka")
    },
    {
        title: "Shikikan Sore Irete Mite",
        id: "shikikan-sore-irete-mite",
        hidden: true,
        japaneseTitle: "Shikikan Sore Irete Mite",
        artists: ["Fummy"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Shikikan Sore Irete Mite"),
        volumeCount: 1,
        volumes: getVolumes("Shikikan Sore Irete Mite")
    },
    {
        title: "Shiro Kyou kara Kodomo Onaho ni Naru",
        id: "shiro-kyou-kara-kodomo-onaho-ni-naru",
        hidden: true,
        japaneseTitle: "「しろ…きょうからこどもおなほに、なる」",
        artists: ["Yuizaki Kazuya"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Shiro Kyou kara Kodomo Onaho ni Naru"),
        volumeCount: 1,
        volumes: getVolumes("Shiro Kyou kara Kodomo Onaho ni Naru")
    },
    {
        title: "Sukisuki Onii-chan",
        id: "sukisuki-onii-chan",
        hidden: true,
        japaneseTitle: "すきすきおにいちゃん",
        artists: ["Minami"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Sukisuki Onii-chan"),
        volumeCount: 1,
        volumes: getVolumes("Sukisuki Onii-chan")
    },
    {
        title: "Umaruchan! For Adult",
        id: "umaruchan!-for-adult",
        hidden: true,
        japaneseTitle: "うまるちゃんと海老名ちゃん! ふぉーあだると",
        artists: ["Hisama Kumako"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Umaruchan! For Adult"),
        volumeCount: 1,
        volumes: getVolumes("Umaruchan! For Adult")
    },
    {
        title: "Yuudachi wa Teitoku-san ga Daisukippoi!",
        id: "yuudachi-wa-teitoku-san-ga-daisukippoi!",
        hidden: true,
        japaneseTitle: "夕立は提督さんが大好きっぽい！",
        artists: ["Tsurusaki Takahiro"],
        published: "",
        added: "2023-02-01T06:34:28.687Z",
        genres: ["Hentai"],
        synopsis: "Hentai.",
        synopsisSource: "",
        website: "",
        cover: getCover("Yuudachi wa Teitoku-san ga Daisukippoi!"),
        volumeCount: 1,
        volumes: getVolumes("Yuudachi wa Teitoku-san ga Daisukippoi!")
    }
]